---
version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.5.4
    steps:
      - checkout
      - run:
          name: Validate base
          command: |
            packer validate \
            -var "aws_region=${aws_region}" \
            -var "aws_access_key=${aws_access_key}" \
            -var "aws_secret_key=${aws_secret_key}" \
            -var "source_ami=${source_ami}" \
            -var "subnet_id=${subnet_id}" \
            ubuntu-ami.json
      - run:
          name: Packer Build
          command: |
            packer build \
            -var "aws_region=${aws_region}" \
            -var "aws_access_key=${aws_access_key}" \
            -var "aws_secret_key=${aws_secret_key}" \
            -var "source_ami=${source_ami}" \
            -var "subnet_id=${subnet_id}" \
            ubuntu-ami.json
workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master