---
version: 2
jobs:
  build:
    docker:
      - image: hashicorp/packer:1.5.4
    steps:
      - checkout
      - run:
          name: Validate base
          command: packer validate ./ubuntu-ami.json
workflows:
  version: 2
  build_deploy:
    jobs:
      - build:
          filters:
            branches:
              only: master